// <auto-generated />
using LuuTienDat_174.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuuTienDat_174.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106071441_Create_Table_SinhVienHumg")]
    partial class Create_Table_SinhVienHumg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LuuTienDat_174.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<double>("Diem")
                        .HasColumnType("REAL");

                    b.Property<int>("SoBaoDanh")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaSinhVien");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("LuuTienDat_174.Models.SinhVienHumg", b =>
                {
                    b.Property<int>("SoThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SoThuTu");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("SinhVienHumgs");
                });

            modelBuilder.Entity("LuuTienDat_174.Models.SinhVienHumg", b =>
                {
                    b.HasOne("LuuTienDat_174.Models.SinhVien", "SinhVien")
                        .WithMany("SinhVienHumg")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("LuuTienDat_174.Models.SinhVien", b =>
                {
                    b.Navigation("SinhVienHumg");
                });
#pragma warning restore 612, 618
        }
    }
}
