// <auto-generated />
using LuuTienDat_174.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuuTienDat_174.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240106071027_Create_Table_SinhVien")]
    partial class Create_Table_SinhVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LuuTienDat_174.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<double>("Diem")
                        .HasColumnType("REAL");

                    b.Property<int>("SoBaoDanh")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaSinhVien");

                    b.ToTable("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
